// t_1c27edbf (V0 fase v3): diccionario i18n base del chrome + placeholders.
// Fuente EN: referencia krumm_frontend.zip v2 (docs/spec/frontend-ref-v2/script.js,
// bloque "en"); ES: mismo bloque "es" de la referencia (reutilizado textualmente)
// + las páginas nuevas de la fase. Regla del plan maestro §3-V0: "Copys EN de la
// referencia + diccionario ES (t(es,en))".
//
// Convenciones (plan V0, decisión 2):
// - Claves planas espejo de la referencia (cp_*, company_*, portal_*) + `pages`
//   anidado para los placeholders (title/note/backLabel por ruta).
// - Los componentes V0/V1..V4 consumen el diccionario vía useV3Copy() (hook sobre
//   useLanguage); las cadenas one-shot fuera del diccionario usan t(es, en).
// - V1–V4 amplían este módulo con sus claves de contenido (pl_*, pd_*, request_*).
import { useLanguage } from '../i18n/LanguageContext.jsx';

const EN = Object.freeze({
  // ── común ────────────────────────────────────────────────────────────────
  common_skipContent: 'Skip to content',
  common_logoAlt: 'KRUMM — Tech for talent assessment',
  common_language: 'Language',
  common_close: 'Close',
  common_krumm: 'KRUMM',
  common_footerYear: '© 2026 KRUMM',
  common_nextIteration: 'This experience will be developed in the next iteration.',
  common_backHome: '← Back to KRUMM',
  common_backPortals: '← Choose another portal',
  // ── chrome candidato (ref: candidate.html + candidate.js) ────────────────
  cp_breadcrumb: 'Breadcrumb',
  cp_help: 'Help',
  cp_helpText: 'Choose “View opportunities” to explore available roles, or “Sign in” if you already have an invitation.',
  cp_privacy: 'Privacy notice',
  cp_terms: 'Terms',
  cp_candidatePortal: 'Candidate portal',
  cp_access: 'Candidate access',
  cp_jobs: 'Job board',
  cp_back: 'Back to candidate portal',
  cp_eyebrow: 'KRUMM · TALENT ASSESSMENT',
  // ── home candidato V1 (ref: candidate.html — copias textuales) ──────────
  cp_title: 'Find your next opportunity.',
  cp_subtitle: "Explore available hiring processes or access an assessment you've been invited to.",
  cp_question: 'How would you like to continue?',
  cp_explore: 'Explore opportunities',
  cp_exploreText: "Browse KRUMM's available hiring processes and find an opportunity that matches your profile.",
  cp_exploreAction: 'View opportunities',
  cp_exploreHint: 'Explore available roles',
  cp_invitation: 'I already have an invitation',
  cp_invitationText: "Access the hiring process you've been invited to and start your assessment.",
  cp_signIn: 'Sign in',
  cp_invitationHint: 'Did you receive a KRUMM invitation link?',
  // ── acceso candidato V1 (form de invitación; ref login-candidate.html es
  //    placeholder → copias nuevas honestas, sin auth inventada) ──────────
  ca_intro: 'Paste the invitation link or token you received and we will validate it to start your assessment.',
  ca_label: 'Invitation link or token',
  ca_inputPlaceholder: 'https://…/postulaciones?invite=your-token',
  ca_formatError: 'That does not look like an invitation link or token. Check it and try again.',
  ca_note: 'The link is validated before starting your assessment.',
  // ── chrome empresa (ref: company.html + company.js) ──────────────────────
  company_workspace: 'Company workspace',
  company_dashboard: 'Dashboard',
  company_newRequest: 'New request',
  company_processes: 'Processes',
  company_settings: 'Settings',
  company_help: 'Help',
  company_account: 'Account',
  company_notifications: 'Notifications',
  company_signOut: 'Sign out',
  company_openNavigation: 'Toggle navigation',
  company_portalNavigation: 'Company navigation',
  company_breadcrumb: 'Breadcrumb',
  company_demoBadge: 'Demo workspace',
  company_demoNotice: 'All names, processes and results shown here are fictional.',
  company_previewTitle: 'Next in the preview',
  company_previewText: 'This screen will be designed in the next stage. For now, you can explore the dashboard.',
  company_notificationsText: 'You’re all caught up. This is a visual preview of your notification center.',
  company_accountText: 'Demo account · People & Culture · Andes Industries',
  company_userName: 'Alex Morgan',
  company_userOrg: 'Andes Industries',
  company_userInitials: 'AM',
  company_eyebrow: 'ANDES INDUSTRIES',
  company_enterDemo: 'Explore company demo →',
  company_comingSoon: 'Coming soon',
  company_loginPreview: 'This portal is being prepared. Sign-in will be available here soon.',
  company_processesTitle: 'Active processes',
  company_processDetail: 'Process detail',
  company_processReport: 'Candidate report',
  company_requestDesign: 'New request · Design with KRUMM',
  company_requestUpload: 'New request · Upload profile',
  company_backDashboard: 'Back to dashboard',
  // ── V2: dashboard + procesos empresa (ref: company.html + processes.html,
  //    bloque "en" de script.js; copias textuales donde la ref define) ────
  company_overview: 'Overview of your active talent processes.',
  company_activeProcesses: 'Active processes',
  company_evaluated: 'Candidates evaluated',
  company_averageScore: 'Average score',
  company_recommended: 'Candidates recommended',
  company_openSearches: 'Across your workspace',
  company_completedAssessments: 'Completed assessments',
  company_krummScore: 'KRUMM score',
  company_readyReview: 'Ready for review',
  company_processSubtitle: 'A closer look at your ongoing searches.',
  company_viewAll: 'View all processes',
  company_position: 'Position',
  company_candidates: 'Candidates',
  company_status: 'Status',
  company_action: 'Action',
  company_active: 'Active',
  company_viewProcess: 'View process',
  company_viewReport: 'View report',
  company_supervisor: 'Plant Supervisor',
  company_operator: 'Plant Operator',
  company_technician: 'Maintenance Technician',
  company_unspecifiedRole: 'Unspecified role',
  company_loading: 'Loading sessions…',
  company_liveBadge: 'Live sessions (staging)',
  company_liveNotice: 'Aggregated data from the staging API. Human review only — no automated decisions.',
  pl_intro: 'Review your searches, filter the list and open each process.',
  pl_search: 'Search by role or location',
  pl_area: 'All departments',
  pl_location: 'All locations',
  pl_sort: 'Sort by',
  pl_recent: 'Newest first',
  pl_oldest: 'Oldest first',
  pl_candidates: 'Most candidates',
  pl_score: 'Highest average score',
  pl_name: 'Role A–Z',
  pl_reset: 'Clear filters',
  pl_results: 'Processes shown',
  pl_empty: 'No processes match these filters.',
  pl_back: 'Back to processes',
  pd_department: 'Department',
  pd_operations: 'Operations',
  pd_maintenance: 'Maintenance',
  pd_location: 'Location',
  pd_evaluated: 'Evaluated',
  common_tagline: 'Tech for Talent Assessment',
  // ── V3: detalle de proceso (ref process-detail*.html + script.js pd_/pa_) ──
  pd_subtitlePrefix: 'Hiring process ·',
  pd_createdOn: 'Created on ',
  pd_daysActive: 'days active',
  pd_days: 'Days active',
  pd_since: 'Since the process started',
  pd_received: 'Applications received',
  pd_applicants: 'Applicants',
  pd_pending: 'Pending',
  pd_configuration: 'Process configuration',
  pd_configurationSubtitle: 'Information and criteria defined for this search.',
  pd_editConfig: 'Edit configuration',
  pd_role: 'Role',
  pd_mode: 'Work mode',
  pd_profile: 'Target profile',
  pd_statistics: 'Process statistics',
  pd_statisticsSubtitle: 'An overview of application activity.',
  pd_candidateStatus: 'Candidate status',
  pd_distribution: 'Score distribution',
  pd_averageTime: 'Average evaluation time',
  pd_perCandidate: 'Per evaluated candidate',
  pd_recommended: 'Recommended candidates',
  pd_rankingSubtitle: 'Ranking based on observed fit with the target profile.',
  pd_fit: 'Profile fit',
  pd_excellent: 'Excellent',
  pd_veryGood: 'Very good',
  pd_good: 'Good',
  pd_fair: 'Fair',
  pd_allCandidates: 'View all candidates',
  pd_pause: 'Pause process',
  pd_edit: 'Edit process',
  pd_actions: 'Process actions',
  pd_more: 'More process actions',
  pd_backProcess: 'Back to process',
  pd_mockAction: 'Visual preview only. No changes have been made to the process.',
  pd_evaluatedStatus: 'Evaluated',
  pd_minutes: 'min',
  pd_notFound: 'Process not found',
  pd_notFoundText: 'This process does not exist in this workspace. Go back to the process list.',
  pd_report: 'Candidate report',
  pd_reportNotFound: 'Report not found',
  pd_reportNotFoundText: 'This session does not exist in this workspace. Go back to the process.',
  pd_metrics: 'Process metrics',
  pa_title: 'Advanced statistics',
  pa_intro: 'Explore the demographic, experience and cognitive skill distribution.',
  pa_note: 'Fictional aggregate data for this demo. Cognitive percentages show presence among evaluated candidates; they are not selection criteria.',
  pa_age: 'Average age',
  pa_years: 'years',
  pa_experience: 'Average experience',
  pa_ageDistribution: 'Age distribution · all applicants',
  pa_experienceDistribution: 'Years of experience · all applicants',
  pa_present: 'Most present cognitive skills',
  pa_scarce: 'Least present cognitive skills',
  pa_attention: 'Sustained attention',
  pa_reasoning: 'Logical reasoning',
  pa_memory: 'Working memory',
  pa_flexibility: 'Cognitive flexibility',
  pa_planning: 'Planning',
  pa_speed: 'Processing speed',
  // ── portal bare (ref: portal.html + login-company.html) ──────────────────
  portal_title: 'Choose your portal',
  portal_subtitle: 'Access your KRUMM workspace.',
  portal_companies: 'Companies',
  portal_company: 'Company Portal',
  portal_companyDescription: 'Manage assessments, candidates, results and teams.',
  portal_companyCta: 'Sign in as a company →',
  portal_candidates: 'Candidates',
  portal_candidate: 'Candidate Portal',
  portal_candidateDescription: 'Access your assessments and KRUMM experiences.',
  portal_candidateCta: 'Explore candidate portal →',
  // ── placeholders por ruta (plan maestro §2: contenido real en V1–V4) ─────
  pages: Object.freeze({
    candidateHome: Object.freeze({
      title: 'Candidate portal',
      note: 'This experience will be developed in the next iteration.',
      backLabel: 'Back to candidate portal',
    }),
    candidateAccess: Object.freeze({
      title: 'Candidate access',
      note: 'This experience will be developed in the next iteration.',
      backLabel: 'Back to candidate portal',
    }),
    jobs: Object.freeze({
      title: 'Job board',
      note: 'This experience will be developed in the next iteration.',
      backLabel: 'Back to candidate portal',
    }),
    dashboard: Object.freeze({
      title: 'Dashboard',
    }),
    processes: Object.freeze({
      title: 'Active processes',
      note: 'This screen will be designed in the next stage.',
      backLabel: 'Back to dashboard',
    }),
    processDetail: Object.freeze({
      title: 'Process detail',
      note: 'This screen will be designed in the next stage.',
      backLabel: 'Back to dashboard',
    }),
    processReport: Object.freeze({
      title: 'Candidate report',
      note: 'This screen will be designed in the next stage.',
      backLabel: 'Back to dashboard',
    }),
    newRequest: Object.freeze({
      title: 'New request',
      note: 'This screen will be designed in the next stage.',
      backLabel: 'Back to dashboard',
    }),
    requestDesign: Object.freeze({
      title: 'New request · Design with KRUMM',
      note: 'This screen will be designed in the next stage.',
      backLabel: 'Back to dashboard',
    }),
    requestUpload: Object.freeze({
      title: 'New request · Upload profile',
      note: 'This screen will be designed in the next stage.',
      backLabel: 'Back to dashboard',
    }),
    portal: Object.freeze({
      title: 'Choose your portal',
      subtitle: 'Access your KRUMM workspace.',
    }),
    companyAccess: Object.freeze({
      title: 'Company Portal',
      comingSoon: 'Coming soon',
      preview: 'This portal is being prepared. Sign-in will be available here soon.',
      cta: 'Explore company demo →',
      backLabel: '← Choose another portal',
    }),
  }),
});

const ES = Object.freeze({
  // ── común ────────────────────────────────────────────────────────────────
  common_skipContent: 'Ir al contenido',
  common_logoAlt: 'KRUMM — Tecnología para la evaluación de talento',
  common_language: 'Idioma',
  common_close: 'Cerrar',
  common_krumm: 'KRUMM',
  common_footerYear: '© 2026 KRUMM',
  common_nextIteration: 'Esta experiencia será desarrollada en la siguiente iteración.',
  common_backHome: '← Volver a KRUMM',
  common_backPortals: '← Elegir otro portal',
  // ── chrome candidato ─────────────────────────────────────────────────────
  cp_breadcrumb: 'Ruta de navegación',
  cp_help: 'Ayuda',
  cp_helpText: 'Elige «Ver oportunidades» para explorar cargos disponibles o «Iniciar sesión» si ya tienes una invitación.',
  cp_privacy: 'Aviso de privacidad',
  cp_terms: 'Términos',
  cp_candidatePortal: 'Portal para candidatos',
  cp_access: 'Acceso candidato',
  cp_jobs: 'Bolsa de empleos',
  cp_back: 'Volver al portal candidato',
  cp_eyebrow: 'KRUMM · EVALUACIÓN DE TALENTO',
  // ── home candidato V1 (ref: candidate.html — copias textuales ES) ────────
  cp_title: 'Encuentra tu próxima oportunidad.',
  cp_subtitle: 'Explora procesos de selección disponibles o accede directamente a una evaluación a la que fuiste invitado.',
  cp_question: '¿Cómo quieres continuar?',
  cp_explore: 'Explorar oportunidades',
  cp_exploreText: 'Revisa los procesos de selección disponibles en KRUMM y encuentra una oportunidad que se ajuste a tu perfil.',
  cp_exploreAction: 'Ver oportunidades',
  cp_exploreHint: 'Explora los cargos disponibles',
  cp_invitation: 'Ya tengo una invitación',
  cp_invitationText: 'Accede al proceso de selección al que fuiste invitado e inicia tu evaluación.',
  cp_signIn: 'Iniciar sesión',
  cp_invitationHint: '¿Recibiste un enlace de KRUMM?',
  // ── acceso candidato V1 (form de invitación) ─────────────────────────────
  ca_intro: 'Pega el enlace de invitación o el token que recibiste y lo validaremos para iniciar tu evaluación.',
  ca_label: 'Enlace o token de invitación',
  ca_inputPlaceholder: 'https://…/postulaciones?invite=tu-token',
  ca_formatError: 'Eso no parece un enlace o token de invitación. Revísalo e inténtalo de nuevo.',
  ca_note: 'El enlace se valida antes de iniciar tu evaluación.',
  // ── chrome empresa ───────────────────────────────────────────────────────
  company_workspace: 'Espacio de empresa',
  company_dashboard: 'Dashboard',
  company_newRequest: 'Nueva solicitud',
  company_processes: 'Procesos',
  company_settings: 'Configuración',
  company_help: 'Ayuda',
  company_account: 'Cuenta',
  company_notifications: 'Notificaciones',
  company_signOut: 'Cerrar sesión',
  company_openNavigation: 'Mostrar u ocultar navegación',
  company_portalNavigation: 'Navegación de empresa',
  company_breadcrumb: 'Ruta de navegación',
  company_demoBadge: 'Espacio de demostración',
  company_demoNotice: 'Todos los nombres, procesos y resultados mostrados son ficticios.',
  company_previewTitle: 'Próximamente en la vista previa',
  company_previewText: 'Esta pantalla se diseñará en la siguiente etapa. Por ahora, puedes explorar el dashboard.',
  company_notificationsText: 'Estás al día. Esta es una vista previa visual del centro de notificaciones.',
  company_accountText: 'Cuenta de demostración · Gestión de Personas · Andes Industries',
  company_userName: 'Alex Morgan',
  company_userOrg: 'Andes Industries',
  company_userInitials: 'AM',
  company_eyebrow: 'ANDES INDUSTRIES',
  company_enterDemo: 'Explorar demo de empresas →',
  company_comingSoon: 'Próximamente',
  company_loginPreview: 'Estamos preparando este portal. Pronto podrás iniciar sesión aquí.',
  company_processesTitle: 'Procesos activos',
  company_processDetail: 'Detalle del proceso',
  company_processReport: 'Informe del candidato',
  company_requestDesign: 'Nueva solicitud · Diseñar con KRUMM',
  company_requestUpload: 'Nueva solicitud · Subir perfil',
  company_backDashboard: 'Volver al dashboard',
  // ── V2: dashboard + procesos empresa (bloque "es" de script.js de la ref) ──
  company_overview: 'Una vista general de tus procesos de talento activos.',
  company_activeProcesses: 'Procesos activos',
  company_evaluated: 'Candidatos evaluados',
  company_averageScore: 'Puntaje promedio',
  company_recommended: 'Candidatos recomendados',
  company_openSearches: 'En tu espacio de trabajo',
  company_completedAssessments: 'Evaluaciones completadas',
  company_krummScore: 'Puntaje KRUMM',
  company_readyReview: 'Listos para revisión',
  company_processSubtitle: 'Una mirada a tus búsquedas en curso.',
  company_viewAll: 'Ver todos los procesos',
  company_position: 'Cargo',
  company_candidates: 'Candidatos',
  company_status: 'Estado',
  company_action: 'Acción',
  company_active: 'Activo',
  company_viewProcess: 'Ver proceso',
  company_viewReport: 'Ver informe',
  company_supervisor: 'Supervisor de Planta',
  company_operator: 'Operador de Planta',
  company_technician: 'Técnico de Mantención',
  company_unspecifiedRole: 'Cargo no especificado',
  company_loading: 'Cargando sesiones…',
  company_liveBadge: 'Sesiones reales (staging)',
  company_liveNotice: 'Datos agregados de la API de staging. Solo revisión humana, sin decisiones automáticas.',
  pl_intro: 'Revisa tus búsquedas, filtra la lista y accede a cada proceso.',
  pl_search: 'Buscar por cargo o ubicación',
  pl_area: 'Todas las áreas',
  pl_location: 'Todas las ubicaciones',
  pl_sort: 'Ordenar por',
  pl_recent: 'Más recientes',
  pl_oldest: 'Más antiguos',
  pl_candidates: 'Más candidatos',
  pl_score: 'Mayor puntaje promedio',
  pl_name: 'Cargo A–Z',
  pl_reset: 'Limpiar filtros',
  pl_results: 'Procesos encontrados',
  pl_empty: 'No hay procesos que coincidan con estos filtros.',
  pl_back: 'Volver a procesos',
  pd_department: 'Área',
  pd_operations: 'Operaciones',
  pd_maintenance: 'Mantenimiento',
  pd_location: 'Ubicación',
  pd_evaluated: 'Evaluados',
  common_tagline: 'Tecnología para la evaluación de talento',
  // ── V3: detalle de proceso (ref process-detail*.html + script.js pd_/pa_) ──
  pd_subtitlePrefix: 'Proceso de selección ·',
  pd_createdOn: 'Creado el ',
  pd_daysActive: 'días activo',
  pd_days: 'Días activo',
  pd_since: 'Desde el inicio del proceso',
  pd_received: 'Postulaciones recibidas',
  pd_applicants: 'Postulantes',
  pd_pending: 'Pendientes',
  pd_configuration: 'Configuración del proceso',
  pd_configurationSubtitle: 'Información y criterios definidos para esta búsqueda.',
  pd_editConfig: 'Editar configuración',
  pd_role: 'Cargo',
  pd_mode: 'Modalidad',
  pd_profile: 'Perfil buscado',
  pd_statistics: 'Estadísticas del proceso',
  pd_statisticsSubtitle: 'Una vista general del comportamiento de las postulaciones.',
  pd_candidateStatus: 'Estado de candidatos',
  pd_distribution: 'Distribución de puntajes',
  pd_averageTime: 'Tiempo promedio de evaluación',
  pd_perCandidate: 'Por candidato evaluado',
  pd_recommended: 'Candidatos recomendados',
  pd_rankingSubtitle: 'Ranking basado en el ajuste observado respecto al perfil buscado.',
  pd_fit: 'Ajuste al perfil',
  pd_excellent: 'Excelente',
  pd_veryGood: 'Muy bueno',
  pd_good: 'Bueno',
  pd_fair: 'Regular',
  pd_allCandidates: 'Ver todos los candidatos',
  pd_pause: 'Pausar proceso',
  pd_edit: 'Editar proceso',
  pd_actions: 'Acciones del proceso',
  pd_more: 'Más acciones del proceso',
  pd_backProcess: 'Volver al proceso',
  pd_mockAction: 'Solo vista previa. No se han realizado cambios en el proceso.',
  pd_evaluatedStatus: 'Evaluado',
  pd_minutes: 'min',
  pd_notFound: 'Proceso no encontrado',
  pd_notFoundText: 'Este proceso no existe en este workspace. Vuelve a la lista de procesos.',
  pd_report: 'Informe del candidato',
  pd_reportNotFound: 'Informe no encontrado',
  pd_reportNotFoundText: 'Esta sesión no existe en este workspace. Vuelve al proceso.',
  pd_metrics: 'Métricas del proceso',
  pa_title: 'Estadísticas avanzadas',
  pa_intro: 'Explora la distribución demográfica, la experiencia y las habilidades cognitivas.',
  pa_note: 'Datos agregados ficticios para esta demo. Los porcentajes cognitivos representan presencia entre los evaluados; no son criterios de selección.',
  pa_age: 'Edad promedio',
  pa_years: 'años',
  pa_experience: 'Experiencia promedio',
  pa_ageDistribution: 'Distribución de edad · todos los postulantes',
  pa_experienceDistribution: 'Años de experiencia · todos los postulantes',
  pa_present: 'Habilidades cognitivas más presentes',
  pa_scarce: 'Habilidades cognitivas más escasas',
  pa_attention: 'Atención sostenida',
  pa_reasoning: 'Razonamiento lógico',
  pa_memory: 'Memoria de trabajo',
  pa_flexibility: 'Flexibilidad cognitiva',
  pa_planning: 'Planificación',
  pa_speed: 'Velocidad de procesamiento',
  // ── portal bare ──────────────────────────────────────────────────────────
  portal_title: 'Elige tu portal',
  portal_subtitle: 'Accede a tu espacio KRUMM.',
  portal_companies: 'Empresas',
  portal_company: 'Portal para empresas',
  portal_companyDescription: 'Gestiona procesos de evaluación, candidatos, resultados y equipos.',
  portal_companyCta: 'Ingresar como empresa →',
  portal_candidates: 'Candidatos',
  portal_candidate: 'Portal para candidatos',
  portal_candidateDescription: 'Accede a tus evaluaciones y experiencias KRUMM.',
  portal_candidateCta: 'Explorar portal candidato →',
  // ── placeholders por ruta ────────────────────────────────────────────────
  pages: Object.freeze({
    candidateHome: Object.freeze({
      title: 'Portal para candidatos',
      note: 'Esta experiencia será desarrollada en la siguiente iteración.',
      backLabel: 'Volver al portal candidato',
    }),
    candidateAccess: Object.freeze({
      title: 'Acceso candidato',
      note: 'Esta experiencia será desarrollada en la siguiente iteración.',
      backLabel: 'Volver al portal candidato',
    }),
    jobs: Object.freeze({
      title: 'Bolsa de empleos',
      note: 'Esta experiencia será desarrollada en la siguiente iteración.',
      backLabel: 'Volver al portal candidato',
    }),
    dashboard: Object.freeze({
      title: 'Dashboard',
    }),
    processes: Object.freeze({
      title: 'Procesos activos',
      note: 'Esta pantalla se diseñará en la siguiente etapa.',
      backLabel: 'Volver al dashboard',
    }),
    processDetail: Object.freeze({
      title: 'Detalle del proceso',
      note: 'Esta pantalla se diseñará en la siguiente etapa.',
      backLabel: 'Volver al dashboard',
    }),
    processReport: Object.freeze({
      title: 'Informe del candidato',
      note: 'Esta pantalla se diseñará en la siguiente etapa.',
      backLabel: 'Volver al dashboard',
    }),
    newRequest: Object.freeze({
      title: 'Nueva solicitud',
      note: 'Esta pantalla se diseñará en la siguiente etapa.',
      backLabel: 'Volver al dashboard',
    }),
    requestDesign: Object.freeze({
      title: 'Nueva solicitud · Diseñar con KRUMM',
      note: 'Esta pantalla se diseñará en la siguiente etapa.',
      backLabel: 'Volver al dashboard',
    }),
    requestUpload: Object.freeze({
      title: 'Nueva solicitud · Subir perfil',
      note: 'Esta pantalla se diseñará en la siguiente etapa.',
      backLabel: 'Volver al dashboard',
    }),
    portal: Object.freeze({
      title: 'Elige tu portal',
      subtitle: 'Accede a tu espacio KRUMM.',
    }),
    companyAccess: Object.freeze({
      title: 'Portal para empresas',
      comingSoon: 'Próximamente',
      preview: 'Estamos preparando este portal. Pronto podrás iniciar sesión aquí.',
      cta: 'Explorar demo de empresas →',
      backLabel: '← Elegir otro portal',
    }),
  }),
});

export const V3_COPY = Object.freeze({ en: EN, es: ES });

export function getV3Copy(language) {
  if (language === 'es') return V3_COPY.es;
  if (language === 'en') return V3_COPY.en;
  return V3_COPY.es;
}

export function useV3Copy() {
  const { language } = useLanguage();
  return getV3Copy(language);
}

// Arboleda plana de claves (path.join('.')) — para tests de paridad externas.
export function flattenKeys(node, prefix = '', out = []) {
  for (const [key, value] of Object.entries(node)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'string') out.push(path);
    else if (value && typeof value === 'object') flattenKeys(value, path, out);
  }
  return out;
}
